- hosts: all
  become: true
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: present

    - name: install httpd
      yum:
         name: httpd
         state: present
