- hosts: all
  become: true
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: present
      tags: ['never','ftp']

    - name: install httpd
      yum:
         name: httpd
         state: present
      tags: ['never','web']
